#!/bin/bash

# IT_FILES = Manually tested cases
# HW2_FILES = AFL generated cases
# * Note: Delete original test cases in queue folders before running

IT_FILES=hw2_initial_files/
HW2_FILES=hw2_pngs/

IT_PNGS=hw2_initial_files/*.png
HW2_PNGS=hw2_pngs/*.png

PREV_COVERAGE=`grep -n 'Lines executed' hw2_previous_test_coverage.txt | tail -1`

rm *.gcda pngout.png new_test_coverage.txt

# Iterate through every test file produced from AFL
for f in $HW2_PNGS
do
   echo $f
   # Put file into IT_FILES
   cp -r $f $IT_FILES

   # Run gcov for all IT_PNGS
   for x in $IT_PNGS
   do
      ./pngtest $x
   done
   
   # Compare "previous_test_coverage.txt" to "new_test_coverage.txt"
   gcov -m *.c > new_test_coverage.txt

   new_coverage=`grep -n 'Lines executed' new_test_coverage.txt | tail -1`
   echo $f >> hw2_coverage_diff.txt
   echo "   $new_coverage" >> hw2_coverage_diff.txt

   if [[ "$new_coverage" == "$PREV_COVERAGE" ]]
   then
      echo "Matching coverage!"
      echo "FILE - $f"
   else
      echo "Unmatching coverage!"
      echo "FILE - $f"
   fi

   # If the last line of grep for each is different, then echo the file and break;
   # Else, remove file from HW2_FILES
   rm hw2_initial_files/id*
   rm *.gcda pngout.png new_test_coverage.txt
done

echo "Completed!"